language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"

install:
  - pip install .

script:
  - python setup.py test

after_success:
- echo "Success!"

after_failure:
- echo "Failure!"

#after_script:
#- Put clean-up or finalization commands here
